import { colors, radii, spacing } from "@evolyfoot/design-tokens";
import { demoFocus, demoTeam, nextSession } from "@evolyfoot/domain";
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Link } from "expo-router";

export default function HomeScreen() {
  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.page}>
        <View style={styles.header}><View><Text style={styles.eyebrow}>LUNDI 17 AOÛT</Text><Text style={styles.title}>Bonjour Abdes,</Text><Text style={styles.subtitle}>{demoTeam.name} · {demoTeam.ageGroup}</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>AM</Text></View></View>
        <View style={styles.focusCard}><Text style={styles.focusEyebrow}>PRIORITÉ DU CYCLE · SEMAINE 3/4</Text><Text style={styles.focusTitle}>{demoFocus.label}</Text><Text style={styles.focusBody}>Faire émerger davantage de soutien proche et de solutions devant le ballon.</Text><View style={styles.progress}><View style={[styles.progressValue, { width: `${demoFocus.progress}%` }]} /></View><View style={styles.row}><Text style={styles.focusMeta}>{demoFocus.sessionsCompleted}/{demoFocus.sessionsTotal} séances</Text><Text style={styles.focusMeta}>{demoFocus.progress}%</Text></View></View>
        <Text style={styles.sectionTitle}>Prochaine séance</Text>
        <View style={styles.sessionCard}><View style={styles.row}><Text style={styles.eyebrow}>{nextSession.dateLabel.toUpperCase()}</Text><Text style={styles.chip}>{nextSession.intensity}</Text></View><Text style={styles.cardTitle}>{nextSession.title}</Text><Text style={styles.cardBody}>{nextSession.durationMinutes} min · {nextSession.playerCount} joueurs · Jeu de position</Text><TouchableOpacity style={styles.button}><Text style={styles.buttonText}>Ouvrir la séance</Text><Text style={styles.buttonText}>→</Text></TouchableOpacity></View>
        <View style={styles.suggestion}><View style={styles.spark}><Text>✦</Text></View><View style={styles.suggestionContent}><Text style={styles.eyebrow}>SUGGESTION EVOLY</Text><Text style={styles.suggestionTitle}>Garde le thème, change la contrainte.</Text><Text style={styles.cardBody}>Réduis l&apos;espace mardi pour provoquer des décisions plus rapides.</Text></View></View>
        <Link href="/onboarding" asChild><TouchableOpacity style={styles.setupButton}><Text style={styles.setupText}>Configurer mon équipe</Text><Text style={styles.setupText}>→</Text></TouchableOpacity></Link>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe:{flex:1,backgroundColor:colors.paper},page:{padding:spacing.lg,paddingBottom:48},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:spacing.xl},eyebrow:{fontSize:10,letterSpacing:1.2,fontWeight:"800",color:colors.muted},title:{fontSize:28,fontWeight:"800",color:colors.ink,marginTop:6},subtitle:{fontSize:13,color:colors.muted,marginTop:4},avatar:{width:42,height:42,borderRadius:21,backgroundColor:colors.primarySoft,alignItems:"center",justifyContent:"center"},avatarText:{color:colors.primary,fontSize:11,fontWeight:"800"},focusCard:{padding:spacing.lg,borderRadius:radii.lg,backgroundColor:colors.primary},focusEyebrow:{fontSize:9,letterSpacing:1,color:"#c2decf",fontWeight:"800"},focusTitle:{fontSize:23,lineHeight:29,fontWeight:"800",color:"white",marginTop:24},focusBody:{fontSize:12,lineHeight:19,color:"#cfe0d6",marginTop:10},progress:{height:6,borderRadius:3,backgroundColor:"rgba(255,255,255,.18)",marginTop:24,overflow:"hidden"},progressValue:{height:6,backgroundColor:colors.lime,borderRadius:3},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},focusMeta:{fontSize:10,color:"#d7e4db",marginTop:10},sectionTitle:{fontSize:18,fontWeight:"800",color:colors.ink,marginTop:32,marginBottom:14},sessionCard:{padding:spacing.lg,backgroundColor:colors.surface,borderRadius:radii.md,borderWidth:1,borderColor:colors.line},chip:{fontSize:9,fontWeight:"800",color:colors.primary,backgroundColor:colors.primarySoft,paddingVertical:6,paddingHorizontal:9,borderRadius:radii.pill},cardTitle:{fontSize:20,fontWeight:"800",color:colors.ink,marginTop:20},cardBody:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:8},button:{marginTop:22,padding:14,backgroundColor:colors.ink,borderRadius:radii.sm,flexDirection:"row",justifyContent:"space-between"},buttonText:{fontSize:11,fontWeight:"800",color:"white"},suggestion:{flexDirection:"row",gap:12,backgroundColor:"#e8f0df",padding:spacing.md,borderRadius:radii.md,marginTop:16},spark:{width:34,height:34,borderRadius:10,backgroundColor:colors.lime,alignItems:"center",justifyContent:"center"},suggestionContent:{flex:1},suggestionTitle:{fontSize:14,fontWeight:"800",color:colors.ink,marginTop:5},setupButton:{marginTop:16,padding:15,backgroundColor:colors.ink,borderRadius:radii.sm,flexDirection:"row",justifyContent:"space-between"},setupText:{color:"white",fontSize:11,fontWeight:"800"}
});
