import { ageGroups, type AgeGroup } from "@evolyfoot/domain";
import { colors, radii, spacing } from "@evolyfoot/design-tokens";
import { useState } from "react";
import { Link } from "expo-router";
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
export default function OnboardingScreen() {
  const [name,setName]=useState(""); const [ageGroup,setAgeGroup]=useState<AgeGroup>("U12");
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Text style={styles.step}>ÉTAPE 1 SUR 3</Text><Text style={styles.title}>Commençons par ton équipe.</Text><Text style={styles.body}>Ces repères permettront d’adapter le futur plan de progression.</Text><Text style={styles.label}>Nom de l’équipe</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Ex. FC Horizon"/><Text style={styles.label}>Catégorie</Text><View style={styles.choices}>{ageGroups.map((group)=><TouchableOpacity key={group} onPress={()=>setAgeGroup(group)} style={[styles.choice,ageGroup===group&&styles.active]}><Text style={[styles.choiceText,ageGroup===group&&styles.activeText]}>{group}</Text></TouchableOpacity>)}</View><Link href="/diagnostic" asChild><TouchableOpacity style={styles.button}><Text style={styles.buttonText}>Continuer vers le diagnostic</Text><Text style={styles.buttonText}>→</Text></TouchableOpacity></Link></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},page:{padding:spacing.lg,paddingTop:48},step:{fontSize:10,fontWeight:"800",letterSpacing:1.2,color:colors.primary},title:{fontSize:34,lineHeight:39,fontWeight:"800",color:colors.ink,marginTop:12},body:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:10,marginBottom:36},label:{fontSize:11,fontWeight:"800",color:colors.ink,marginBottom:9,marginTop:20},input:{backgroundColor:colors.surface,borderColor:colors.line,borderWidth:1,borderRadius:radii.sm,padding:14},choices:{flexDirection:"row",gap:8},choice:{flex:1,alignItems:"center",padding:14,backgroundColor:colors.surface,borderColor:colors.line,borderWidth:1,borderRadius:radii.sm},active:{backgroundColor:colors.primarySoft,borderColor:colors.primary},choiceText:{fontSize:11,fontWeight:"800",color:colors.muted},activeText:{color:colors.primary},button:{marginTop:40,padding:16,borderRadius:radii.sm,backgroundColor:colors.ink,flexDirection:"row",justifyContent:"space-between"},buttonText:{color:"white",fontSize:11,fontWeight:"800"}});
